const conditions = [
  "bleed1",
  "bleed2",
  "bleed3",
  "bleed4",
  "blight1",
  "blight2",
  "blight3",
  "blight4",
  "buff",
  "debuff",
  "guard",
  "mark",
  "protection",
  "riposte",
  "stun",
];

const separateCards = [
  { url: (hero) => `${hero}/hero1.webp`, x: 1, y: 1, index: 0 },
  { url: (hero) => `${hero}/hero2.webp`, x: 1, y: 1, index: 0 },
  { url: (hero) => `${hero}/hero3.webp`, x: 1, y: 1, index: 0 },
];
const doubleCards = [
  { url: (hero) => `${hero}/hero.webp`, x: 2, y: 1, index: 0 },
  { url: (hero) => `${hero}/hero2.webp`, x: 2, y: 1, index: 0 },
  { url: (hero) => `${hero}/hero.webp`, x: 2, y: 1, index: 1 },
];
const megaCard1 = { url: () => "mega1.webp", x: 6, y: 4 };
const megaCard2 = { url: () => "mega2.webp", x: 6, y: 4 };
const abominationCard = {
  url: (_, transformed) => (transformed ? "mega2.webp" : "mega1.webp"),
  x: 6,
  y: 4,
};

const heroes = {
  abomination: {
    cardSprite: [
      { ...abominationCard, index: 20 },
      { ...abominationCard, index: 21 },
      { ...abominationCard, index: 22 },
    ],
    abilities: [
      "Manacles",
      "Beast's Bile",
      "Absolution",
      "Transform",
      "Rake",
      "Rage",
      "Slam",
    ],
    abilitiesSize: [7, 3],
    life: [13, 18, 23],
  },
  antiquarian: {
    cardSprite: doubleCards,
    abilities: [
      "Nervous Stab",
      "Festering Vapours",
      "Get Down!",
      "Flashpowder",
      "Fortifying Vapours",
      "Invigorating Vapours",
      "Protect Me",
    ],
    abilitiesSize: [7, 3],
    life: [9, 12, 15],
  },
  arbalest: {
    cardSprite: separateCards,
    abilities: [
      "Sniper Shot",
      "Suppressive Fire",
      "Sniper's Mark",
      "Bola",
      "Blindfire",
      "Battlefield Bandage",
      "Rallying Flare",
    ],
    abilitiesSize: [10, 7],
    life: [14, 19, 24],
  },
  bounty_hunter: {
    cardSprite: [
      { ...megaCard1, index: 4 },
      { ...megaCard2, index: 4 },
      { ...megaCard1, index: 5 },
    ],
    abilities: [
      "Collect Bounty",
      "Mark for Death",
      "Come Hither",
      "Uppercut",
      "Flashbang",
      "Finish Him",
      "Caltrops",
    ],
    abilitiesSize: [7, 3],
    life: [14, 18, 23],
  },
  crusader: {
    cardSprite: separateCards,
    abilities: [
      "Smite",
      "Zealous Accusation",
      "Stunning Blow",
      "Bulwark of Faith",
      "Battle Heal",
      "Holy Lance",
      "Inspiring Cry",
    ],
    abilitiesSize: [10, 7],
    life: [17, 24, 32],
  },
  flagellant: {
    cardSprite: doubleCards,
    abilities: [
      "Punish",
      "Rain of Sorrows",
      "Exsanguinate",
      "Reclaim",
      "Redeem",
      "Endure",
      "Suffer",
    ],
    abilitiesSize: [7, 3],
    life: [12, 16, 22],
  },
  grave_robber: {
    cardSprite: [
      { ...megaCard1, index: 16 },
      { ...megaCard2, index: 16 },
      { ...megaCard1, index: 17 },
    ],
    abilities: [
      "Pick to the Face",
      "Lunge",
      "Flashing Daggers",
      "Shadow Fade",
      "Thrown Dagger",
      "Poison Dart",
      "Toxin Trickery",
    ],
    abilitiesSize: [7, 3],
    life: [11, 15, 19],
  },
  hellion: {
    cardSprite: separateCards,
    abilities: [
      "Wicked Hack",
      "Iron Swan",
      "Barbaric YAWP",
      "If It Bleeds",
      "Breakthrough",
      "Adrenaline Rush",
      "Bleed Out",
    ],
    abilitiesSize: [10, 7],
    life: [14, 18, 24],
  },
  highwayman: {
    cardSprite: separateCards,
    abilities: [
      "Wicked Slice",
      "Pistol Shot",
      "Point Blank Shot",
      "Grapeshot Blast",
      "Tracking Shot",
      "Duelist's Advance",
      "Open Vein",
    ],
    abilitiesSize: [10, 7],
    life: [12, 17, 22],
  },
  houndmaster: {
    cardSprite: doubleCards,
    abilities: [
      "Hound's Rush",
      "Hound's Harry",
      "Target Whistle",
      "Cry Havoc",
      "Guard Dog",
      "Lick Wounds",
      "Blackjack",
    ],
    abilitiesSize: [7, 3],
    life: [11, 15, 19],
  },
  houndmaster_mod: {
    cardSprite: doubleCards,
    abilities: [
      "Hound's Rush",
      "Hound's Harry",
      "Target Whistle",
      "Cry Havoc",
      "Guard Dog",
      "Lick Wounds",
      "Blackjack",
    ],
    abilitiesSize: [7, 3],
    life: [11, 15, 19],
  },
  jester: {
    cardSprite: separateCards,
    abilities: [
      "Dirk Stab",
      "Harvest",
      "Finale",
      "Solo",
      "Slice Off",
      "Battle Ballad",
      "Inspiring Tune",
    ],
    abilitiesSize: [10, 7],
    life: [10, 14, 18],
  },
  leper: {
    cardSprite: doubleCards,
    abilities: [
      "Chop",
      "Hew",
      "Purge",
      "Revenge",
      "Withstand",
      "Solemnity",
      "Intimidate",
    ],
    abilitiesSize: [7, 3],
    life: [18, 25, 33],
  },
  man_at_arms: {
    cardSprite: doubleCards,
    abilities: [
      "Crush",
      "Rampart",
      "Bellow",
      "Defender",
      "Retribution",
      "Command",
      "Bolster",
    ],
    abilitiesSize: [7, 3],
    life: [16, 22, 28],
  },
  occultist: {
    cardSprite: separateCards,
    abilities: [
      "Sacrificial Stab",
      "Abyssal Artilery",
      "Weakening Curse",
      "Wyrd Reconstruction",
      "Vulnerability Hex",
      "Hands from the Abyss",
      "Daemons' Pull",
    ],
    abilitiesSize: [10, 7],
    life: [10, 14, 18],
  },
  plague_doctor: {
    cardSprite: separateCards,
    abilities: [
      "Noxious Blast",
      "Plague Grenade",
      "Blinding Gas",
      "Incision",
      "Battlefield Medicine",
      "Emboldening Vapours",
      "Disorienting Blast",
    ],
    abilitiesSize: [10, 7],
    life: [11, 15, 19],
  },
  shieldbreaker: {
    cardSprite: doubleCards,
    abilities: [
      "Pierce",
      "Puncture",
      "Adder's Kiss",
      "Impale",
      "Expose",
      "Captivate",
      "Serpent Sway",
    ],
    abilitiesSize: [7, 3],
    life: [11, 15, 19],
  },
  vestal: {
    cardSprite: separateCards,
    abilities: [
      "Mace Bash",
      "Judgement",
      "Dazzling Light",
      "Grace",
      "Divine Comfort",
      "Illumination",
      "Hand of Light",
    ],
    abilitiesSize: [10, 7],
    life: [12, 17, 22],
  },
};

// TODO list of lists
const trinketsPool = [
  [
    "Warrior's Cap",
    "Accuracy Stone",
    "Archer's Ring",
    "Bleed Charm",
    "Blight Charm",
    "Caution Cloak",
    "Critical Stone",
    "Damage Stone",
    "Debuff Charm",
    "Sage's Book",
    "Speed Stone",
    "Stun Charm",
    "Survival Guide",
    "Warrior's Bracer",
  ],
  [
    "Solar Bracer",
    "Bloodthirst Ring",
    "Boook of Constitution",
    "Book of Holiness",
    "Book of Relaxation",
    "Camouflage Cloak",
    "Chirurgeon's Charm",
    "Dark Bracer",
    "Protective Padlock",
    "Bloodcourse Medallion",
    "Camper's Helmet",
    "Fortunate Armlet",
  ],
  [
    "Cleansing Crystal",
    "Berserk Charm",
    "Dark Crown",
    "Fasting Seal",
    "Recovery Charm",
    "Sniper's Ring",
    "Warrior's Ring",
    "Defender's Ring",
    "Scholar's Ring",
    "Solar Crown",
    "Book of Sanity",
    "Candle of Life",
  ],
];

const diseases = [
  "Black Plague",
  "Bulimic",
  "Ennui",
  "Hemophilia",
  "Lethargy",
  "Syphilis",
  "Vertigo",
  "The Worries",
  "Creeping Cough",
  "Tapeworm",
  "Spotted Fever",
];

const afflictions = [
  "Fearful",
  "Selfish",
  "Masochistic",
  "Hopeless",
  "Irrational",
];

const virtues = ["Stalwart", "Courageous", "Focused", "Powerful", "Vigorous"];

const negatives = [
  "Anemic",
  "Nocturnal",
  "Clumsy",
  "Off Guard",
  "Infirm",
  "Shocker",
  "Mercurial",
  "Night Blindness",
  "Weak Grip",
  "Slow Reflexes",
  "Nervous",
  "Stress Eater",
  "Thin Blooded",
  "Fragile",
  "Light Sensitive",
  "Fear of the Unknown",
  "Bad Gambler",
  "Soft",
];

const positives = [
  "Clotter",
  "Eartly Riser",
  "Fast Healer",
  "Hard Noggin",
  "Night Owl",
  "Evasive",
  "Photo Mania",
  "Quick Reflexes",
  "Resilient",
  "Stress Faster",
  "Thick Blooded",
  "Hard Skinned",
  "Warrior of Light",
  "Balanced",
  "Hoarder",
  "On Guard",
  "Skilled Gambler",
];

// trinkets positions
const TRINKET_MARGIN = [
  "calc(8 * var(--unit))",
  "calc(3 * var(--unit))",
  "calc(2 * var(--unit))",
];
